// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineJudgeServer.Models;

namespace OnlineJudgeServer.Migrations
{
    [DbContext(typeof(OnlineJudgeContext))]
    [Migration("20190607053457_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineJudgeServer.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("ExampleInput");

                    b.Property<string>("ExampleOutPut");

                    b.Property<string>("Note");

                    b.Property<int>("ProblemId");

                    b.Property<int>("PushlishId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.Submit", b =>
                {
                    b.Property<int>("SubmitId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeSuffix");

                    b.Property<int>("CodeType");

                    b.Property<int>("JudgeStatus");

                    b.Property<int>("ProblemId");

                    b.Property<string>("SourceCode");

                    b.Property<DateTime>("SubmitTime");

                    b.Property<int>("UserId");

                    b.HasKey("SubmitId");

                    b.ToTable("Submits");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<DateTime>("RegisterTime");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
