// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineJudgeServer.Models;

namespace OnlineJudgeServer.Migrations
{
    [DbContext(typeof(OnlineJudgeContext))]
    [Migration("20190606075414_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineJudgeServer.Models.Problem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("ExampleInput");

                    b.Property<string>("ExampleOutPut");

                    b.Property<string>("Note");

                    b.Property<int>("PushlishId");

                    b.Property<string>("Title");

                    b.HasKey("ProblemId");

                    b.ToTable("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
