// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineJudgeServer.Models;

namespace OnlineJudgeServer.Migrations
{
    [DbContext(typeof(OnlineJudgeContext))]
    [Migration("20190919075417_add-problemCategory")]
    partial class addproblemCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineJudgeServer.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcceptSubmit");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<string>("ExampleInput");

                    b.Property<string>("ExampleOutPut");

                    b.Property<int>("MemoryLimit");

                    b.Property<string>("Note");

                    b.Property<int>("ProblemId");

                    b.Property<DateTime>("PublishTime");

                    b.Property<int>("PushlishId");

                    b.Property<int>("TimeLimit");

                    b.Property<string>("Title");

                    b.Property<int>("TotalSubmit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.ProblemCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("TotalProblemNum");

                    b.HasKey("CategoryId");

                    b.ToTable("ProgramCategories");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.Submit", b =>
                {
                    b.Property<int>("SubmitId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeSuffix");

                    b.Property<int>("CodeType");

                    b.Property<string>("JudgeResult");

                    b.Property<int>("JudgeStatus");

                    b.Property<int>("ProblemId");

                    b.Property<string>("SourceCode");

                    b.Property<DateTime>("SubmitTime");

                    b.Property<int>("UserId");

                    b.HasKey("SubmitId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("Submits");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<DateTime>("RegisterTime");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.Problem", b =>
                {
                    b.HasOne("OnlineJudgeServer.Models.ProblemCategory")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineJudgeServer.Models.Submit", b =>
                {
                    b.HasOne("OnlineJudgeServer.Models.Problem")
                        .WithMany("Submits")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineJudgeServer.Models.User")
                        .WithMany("Submits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
